Update namespace documents
w3c/imsc pull request #581
Opened 2023-05-04 17:59 UTC by palemieux

2023-05-05 10:38 UTC, nigelmegitt commented
Would be helpful to make the paths match their eventual destination more closely. Suggest:

|URL|Current path|Proposed path|
|---|---|---|
|`http://www.w3.org/ns/ttml/profile/imsc1/extension/`|`imsc1/spec/imsc-extension-namespace.html`|`profile/imsc1/extension/index.html`|
|`http://www.w3.org/ns/ttml/profile/imsc1.1/image`|`imsc1/spec/imsc-image-namespace.html`|`profile/imsc1.1/image.html`|
|`http://www.w3.org/ns/ttml/profile/imsc1`|`imsc1/spec/imsc-namespace.html`|`profile/imsc1.html`|
|`http://www.w3.org/ns/ttml/profile/imsc1.2/text`|`imsc1/spec/imsc-text-namespace.html`|`profile/imsc1.2/text.html`|

I'm wondering if the trailing `/` in the extension namespace URL is correct, both here and in the IMSC specification?

Also considered: making the path begin with `ns/ttml/profile/` instead of `profile/`.

This is just a suggestion though - any other considerations here @palemieux or @himorin ?

2023-05-05 10:46 UTC, nigelmegitt commented on imsc1/spec/imsc-namespace.html
> +  href="http://www.w3.org/TR/ttml-imsc/">TTML Text and Image Profiles for Internet Media Subtitles and Captions</a>.</p>
In IMSC the base URI is never used on its own. Instead, fragment identifiers are used i.e. each of `#styling`, `#parameter` and `#metadata` are appended to `http://www.w3.org/ns/ttml/profile/imsc1`.

Should we add `<div id="[styling|parameter|metadata]">...</div>` for each, so that the complete URI resolves to something?

And here, state that this document is for the (unused) root of those URIs?

2023-05-05 15:32 UTC, palemieux commented
> I'm wondering if the trailing / in the extension namespace URL is correct, both here and in the IMSC specification?

Yes, the TTML 1 extension namespace (TT Extension) also has a slash: <https://www.w3.org/TR/2018/REC-ttml1-20181108/#vocabulary-namespaces>

2023-05-05 15:36 UTC, nigelmegitt commented
>Yes, the TTML 1 extension namespace (TT Extension) also has a slash

I see, yes, it's used as an `xml:base` - I guess that makes sense. Thanks for checking.

2023-05-05 15:45 UTC, palemieux commented
> Should we add <div id="[styling|parameter|metadata]">...</div> for each, so that the complete URI resolves to something?

See revised text.

2023-05-05 15:51 UTC, nigelmegitt commented on imsc1/spec/imsc-namespace.html
> +    <li><code>http://www.w3.org/ns/ttml/profile/imsc1</code></li>
This one, without the fragment IDs, isn't specified anywhere in IMSC.

2023-05-23 06:36 UTC, himorin commented
@palemieux I suppose we will copy these files into /ns/ space, so how about to open a PR to w3c/ns repository first to ask about lines to be included in namespace documents?
Like, a PR to update https://github.com/w3c/ns/blob/main/ttml/profile/imsc1/extension/Overview.html for `imsc1/spec/imsc-extension-namespace.html`, etc.


(Quite sorry for slow response...)

2023-05-23 16:08 UTC, nigelmegitt requested changes
What do you think about the path change suggestions too, @palemieux ?

2023-05-23 16:08 UTC, nigelmegitt commented on imsc1/spec/imsc-image-namespace.html
> +  href="http://www.w3.org/TR/ttml-imsc1.2/">TTML Text and Image Profiles for Internet Media Subtitles and Captions 1.2</a>.</p>
```suggestion
  <p>The profile designator <code>http://www.w3.org/ns/ttml/profile/imsc1.1/image</code> is specified at <a
  href="http://www.w3.org/TR/ttml-imsc1.1/">TTML Text and Image Profiles for Internet Media Subtitles and Captions 1.1</a>.</p>
```

2023-05-25 15:06 UTC, palemieux commented
> What do you think about the path change suggestions too, @palemieux ?

I do not think it helps very much since the files need to be manually moved to a different tree.

2023-05-25 15:09 UTC, palemieux commented on imsc1/spec/imsc-image-namespace.html
> +  href="http://www.w3.org/TR/ttml-imsc1.2/">TTML Text and Image Profiles for Internet Media Subtitles and Captions 1.2</a>.</p>
The image profile is fully specified in IMSC 1.2, and IMSC 1.2 notes that no substantive changes have not been made since IMSC 1.1, so I think the reference to IMSC 1.2 is appropriate.

2025-01-16 16:25 UTC, palemieux commented
Replaced by #589

2025-01-16 16:25 UTC, closed without merging